* Overview
  Light tiling/stacking window manager for X11 in Common Lisp.
  At this moment I'm studying X11 protocol and window managers written in CL to understand how to implement features listed below.

* Planned features
  Items on this list are numbered according to their priority (the smaller the number, the higher the priority).
  Features that are being considered are marked with "(?)".
  Features 9-11 can be implemented via external programs, but this approach will require partial support for EWMH and/or external scripting of this window manager.

  1. REPL friendly development workflow.
     Code must be split into small functions where it's possible.
     Global variables and X11 resources must be initialized in a separate function.
  2. Convenient and dynamic hotkey definition.
  3. Containers.
  4. Tags or multiple workspaces.
  5. Small rectangular handles around the corners of every managed window.
     These handles allow the user to move and resize floating windows and change stacking layout proportions using the mouse.
     This feature must be implemented without reparenting.
  6. Very basic theming.
     The user must be able to customize the colors of window borders and handles.
  7. Partial EWMH support.
  8. (?) Window switcher.
  9. (?) Status bar.
  10. (?) Pop-up menus.      
